apiVersion: v1
kind: Pod
metadata:
  name: testpod4
  labels:
    env: test
  annotations:
      kubernetes.v1.cni.cncf.io/networks: sriov-net-a sriov-net-a
spec:
  containers:
  - name: appcntr3 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        cpu: "1"
        memory: "512Mi"
        intel.com/sriov_net_A: '2' 
      limits:
        cpu: "1"
        memory: "512Mi"
        intel.com/sriov_net_A: '2'
