apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  labels:
    env: test
  annotations:
      kubernetes.v1.cni.cncf.io/networks: sriov-net-b
spec:
  containers:
  - name: appcntr2 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov_net_B: '1' 
      limits:
        intel.com/sriov_net_B: '1'
