apiVersion: v1
kind: Pod
metadata:
  name: simplepod1
  labels:
    env: test
spec:
  containers:
  - name: container1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
  restartPolicy: "Never"
