---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: kube-system

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-sriov-device-plugin-amd64
  namespace: kube-system
  labels:
    tier: node
    app: sriovdp
spec:
  template:
    metadata:
      labels:
        tier: node
        app: sriovdp
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: sriov-device-plugin
      containers:
      - name: kube-sriovdp
        image: nfvpe/sriov-device-plugin:latest
        imagePullPolicy: Never
        args:
        - --log-dir=sriovdp
        - --log-level=10
        securityContext:
          privileged: false
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/device-plugins/
          readOnly: false
        - name: sysfs
          mountPath: /sys
          readOnly: true
        - name: devfs
          mountPath: /dev
          readOnly: true
        - name: config
          mountPath: /etc/pcidp/config.json
          readOnly: true
        - name: log
          mountPath: /var/log
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins/
        - name: log
          hostPath:
            path: /var/log
        - name: sysfs
          hostPath:
            path: /sys
        - name: devfs
          hostPath:
            path: /dev
        - name: config
          hostPath:
            path: /etc/pcidp/config.json
